name = "crude"

description = "Migration toolkit for databases"
homepage    = "https://github.com/termapps/crude"
license     = "MIT"
repository  = "termapps/crude"

[homebrew]
repository = "termapps/homebrew-tap"
