name: Linting
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@1.75.0
      - name: Lockfile check
        run: cargo update -w --locked
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust
        uses: dtolnay/rust-toolchain@1.75.0
        with:
          components: rustfmt, clippy
      - name: Clippy check
        run: cargo lint
      - name: Format check
        run: cargo format-check
